#! /usr/bin/env bash

# Copyright 2014 Fluo authors (see AUTHORS)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Start: Resolve Script Directory
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
   bin="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
   SOURCE="$(readlink "$SOURCE")"
   [[ $SOURCE != /* ]] && SOURCE="$bin/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
bin="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
script=$( basename "$SOURCE" )
# Stop: Resolve Script Directory

. "$bin"/impl/config.sh

case "$1" in
init)
  "$bin"/impl/init.sh "${*:2}"
	;;
yarn)
  "$bin"/impl/yarn.sh "${*:2}"
	;;
local)
  "$bin"/impl/local.sh "${*:2}"
	;;
*)
	echo -e "Usage: fluo <command> (<argument>)\n"
  echo -e "Possible commands:\n"
	echo "  init      Initializes Fluo instance using conf/fluo.properties"
	echo "  yarn      Administers Fluo instance in YARN"
	echo "  local     Administers Fluo instance on local machine"
  echo " " 
	exit 1
esac
